name: dev_mariadb

services:
  mariadb:
    image: mariadb:latest
    container_name: dev_db
    hostname: devdb
    restart: always
    ports:
      - "3306:3306" # Expose MySQL port
    environment:
      MARIADB_ROOT_PASSWORD: rootpassword
      MARIADB_DATABASE: testdb
      MARIADB_USER: user
      MARIADB_PASSWORD: userpassword
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_network

volumes:
  db_data:
    driver: local
 
networks:
  app_network:
    driver: bridge